spring:
  mail:
    host: smtp.gmail.com
    username: YourEmailAddress
    password: YourPassword
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  auth-code-expiration-millis: 1800000